spring:
  application:
    name: todoapp
  datasource :
    url: jdbc:mysql://localhost:3306/todoapp
    username: root
    password: sankethisapro
  jpa:
    property:
      hibernate:
        ddl-auto: update
        dialect: org.hybernate.dialect.MySQLDilect



